# site settings
title: Perfect Syntax
subtitle: Blog
email: dillon.reedy123@gmail.com
description: A blog about anything on my mind
baseurl: "/dev-blog" # the subpath of your site, e.g. /blog
url: https://dillonreedy.github.io # the base hostname & protocol for your site
author: Dillon Reedy
street_address:
city: Houston
state: TX
zip_code:
country: United States of America
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/dillonreedy
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/dillon-reedy-9037aa114/
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
  - "*.gemspec"
  - LICENSE.md
  - CONTRIBUTING.md
  - README.md
  - package.json
  - package-lock.json
  - /node_modules/*
  - /file-scripts/*
